### ISSUE TITLE
Excluding customs routes ?

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#33]
Hey ! 

All my routes are discovered and documented.

However, I would like to either manually select the ones I want, or exclude the ones I want.

I think the smartest would be to put the routes we want to include or exclude directly in routes.rb?

Or an array in the AOS_RAILS conf with the controller#action to exclude.

**Comment by a-chacon** [comment]
I will be thinking about the best option to implement this. Your idea is perfect, but I can't imagine how to implement it in the routes.rb file. The second option will be another configuration in the initializer file.

**Comment by Metalzoid** [comment]
I think the most convenient method for everyone is to put in the initializer an array like this : 
["controller#action", "controller"]
If controller#action, select or reject this action, if "controller", select or reject all actions on this controller.

It's up to you to decide whether you want to implement a selection or a rejection.

I cloned your repo, but since I'm more than a beginner in rails (especially gems, I don't understand much at the moment), I don't think I'll be of much help ahah

**Comment by phyzical** [comment]
hey looking at this as an alternative to rswag, cool idea.

Just my 2 cents on this, i think the opt in approach is important from a production standpoint.

take a very simple example gem gets added, all its routes auto go into api docs, this might go unnoticed.

or another example. i was thinking i could make logic to go "given the api models defined, expose only their controller routes"

**Comment by phyzical** [comment]
ah i guess we can just use `include_mode =  :with_tags` for my case then add my idea as extra security
