### ISSUE TITLE
schema response ?

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#34]
Hey !

I tryed to include a hash in another hash in the schema response. 
It's supported? I tryed directly : 

`[Hash] {message: String, data: {availabilities: Hash, dates: Hash} }`
Don't work with this.

So far, i've make this =
`[Hash] {message: String, data: Hash, data[availabilities]: Hash, data[dates]: Hash}`

Do you think it's possible include this syntax?
Thanks

**Comment by a-chacon** [comment]
Did you try something like: `[Hash] {message: String, data: { availabilities: Array<String>, dates: Array<String>}}`

I don't remember if that is supported. Is that what you need?

Response Ex:
```
{
  message: "ok",
  data:{
    availabilities: ["9pm", "10pm"],
    dates: ["10/20/20"]
  }
}
```

**Comment by Metalzoid** [comment]
I tryed that : 
`      # @response Availabilities founded.(200) [Hash] {message: String, data: {availabilities: Array<String>, dates: Array<String>}}
`
And the result is : 
`{
"message": "string",
"data": "string",
"dates": "string"
}`

**Comment by Metalzoid** [comment]
Ok! It's not urgent for me 😃 I'm watching this from Monday because busy this weekend ^^
