### ISSUE TITLE
Application production crash after a few hours

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#42]
Hi ! 

I don't know if it's me or my configuration, but in production on a docker container, my app works fine at first, then after a few hours, I have a 404 error (in all pages of my app). This only with oas_rails in production. By disabling oas_rails in production but only in development, I no longer have this problem. I think it comes from RapiDoc?

I have nothing in the logs, not even the requests. Any idea?

Thanks

**Comment by a-chacon** [comment]
What happened?

**Comment by Metalzoid** [comment]
After multiple test, it's my app 😅
