### ISSUE TITLE
Request body documentation

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#46]
Hey ! 

I founded a issue with the request body :)
In the documentation, if i use that : 
```
# @request_body The user to be created [!Hash{user: {name: String, age: Integer, password: String}}]

``` 
the doc return : 
```
{
service: {missing-type-info}
}
``` 

But with that it's ok : 
```
# @request_body The user to be created [!Hash{user: Hash{name: String, age: Integer, password: String}}]
``` 

Thanks !

**Comment by a-chacon** [comment]
The second is the correct way to document it. I change it in the version 0.5 for support deep structures. 

Is there an example with the first structure?

**Comment by Metalzoid** [comment]
Deep structures correctly work :+1: 
Just in your documentation github, it's always this : 
```
# @request_body The user to be created [!Hash{user: {name: String, age: Integer, password: String}}]
``` 
and not that : 
```
# @request_body The user to be created [!Hash{user: Hash{name: String, age: Integer, password: String}}]

```

**Comment by a-chacon** [comment]
ok. mm Is it possible that you fix it please? Is just modify the README file.

**Comment by Metalzoid** [comment]
Make pull request for this =)

**Comment by a-chacon** [comment]
Thank you! Please don't close this manually. I link the PR to the issue and the issue is closed when the PR is merged hehe
