### ISSUE TITLE
Title of Page is Oas rails :) 

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#47]
Hey ! 

Can you add in the config file the title HTML of page /docs ? 
Thanks

**Comment by a-chacon** [comment]
mm I understand the problem, but maybe this is out of scope. You can overwrite the view and put what you want. See [this](https://github.com/a-chacon/oas_rails?tab=readme-ov-file#customizing-the-view) and use the content of the [original file](
https://github.com/a-chacon/oas_rails/blob/main/app/views/oas_rails/oas_rails/index.html.erb)

Just create the index file, put the original content and modify as you need.

**Comment by Metalzoid** [comment]
I make pull request for this =) It's works for me =)
