### ISSUE TITLE
required parameter doesn't work

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#57]
Hey ! 

I found this bug : 
When i try to add required parameter, i've this error : {missing-type-info}

My parameter : 

```ruby
    # @parameter APIKEY(header) [String!] Your admin APIKEY. Here, it's preconfigured for demo.
``` 
thanks

**Comment by a-chacon** [comment]
hi @Metalzoid ! I am sorry, I have to update the documentation. The character `!` is before the type. This changes when we introduce the support for deep structures. All the requirements are before the type for consistence.

So please try something like `[!String]` and give me feedback. I will leave this as a documentation issue.
